### ISSUE TITLE
No need to wait after Wire.requestFrom

### ISSUE THREAD

**Issue by Koepel** [bildr-org/ADJD-S311#1]
In the file ADJDS311.cpp is a while-loop to wait after Wire.requestFrom. That while-loop can be removed.

The Wire.requestFrom is a complete I2C transaction and returns when the I2C transaction has completely finished. The received data is in a buffer in the Wire library.

**Comment by bildr-org** [comment]
Sorry. This article is about 6 years old and probably won't be updated unless it is broken. Because I personally verified every thing posted I won't make changes without verifying the changes as well - But I don't have the hardware anymore to do so.
